name: example
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dio: 5.2.1
  elementary: 2.0.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  logger: 1.4.0
  provider: 6.0.5
  retrofit: 4.0.1
  union_state:
    path: ../

dev_dependencies:
  build_runner: 2.4.6
  elementary_test: 1.1.3
  flutter_test:
    sdk: flutter
  freezed: 2.4.1
  golden_toolkit: 0.15.0
  json_serializable: 6.7.1
  mocktail: 0.3.0
  retrofit_generator: 7.0.8
  surf_lint_rules: 3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mock_data/