name: union_state
description: Universal model to represent basic UI states.
version: 0.0.1
homepage: https://github.com/surfstudio/flutter-union-state

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  elementary: 2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: 3.0.0

flutter:
  uses-material-design: true