name: union_state
description: Universal model to represent basic UI states.
version: 0.0.2
homepage: https://github.com/surfstudio/flutter-union-state

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  surf_lint_rules: ^3.0.0

flutter:
  uses-material-design: true
